name: emfp
channels:
  - mcs07
  - plotly
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.10.1
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=1.0=mkl
  - bleach=4.1.0
  - boost=1.84.0
  - boost-cpp=1.84.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - cmaes=0.9.1
  - colorama=0.4.6
  - colorlog=6.7.0
  - comm=0.1.2
  - contourpy=1.0.5
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - deepsmiles=1.0.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.6.2
  - ffmpeg=4.3
  - fftw=3.3.9
  - filelock=3.12.0
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.80.0
  - glib-tools=2.80.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - greenlet=2.0.1
  - icu=73.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.84.0
  - libboost-devel=1.84.0
  - libboost-headers=1.84.0
  - libboost-python=1.84.0
  - libboost-python-devel=1.84.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.8
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.80.0
  - libgomp=14.1.0
  - libiconv=1.17
  - libnpp=11.7.4.75=0
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.12.6
  - libxslt=1.1.39
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lxml=5.1.0
  - lz4-c=1.9.4
  - mako=1.2.4
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - memory_profiler=0.58.0
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mordred=1.2.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.6
  - networkx=3.1
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - olefile=0.46
  - openbabel=3.1.1
  - openh264=2.1.1
  - openssl=3.3.2
  - optuna=3.1.0
  - packaging=22.0
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - plotly=5.23.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pubchempy=1.0.4
  - pure_eval=0.2.2
  - pycairo=1.21.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=23.2.0
  - readline=8.2
  - reportlab=3.5.67
  - requests=2.31.0
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - selfies=1.0.2
  - send2trash=1.8.0
  - setuptools=65.6.3
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=1.4.39
  - sqlite=3.40.1
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - sympy=1.12
  - tenacity=9.0.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022a
  - urllib3=2.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - combinemols==1.0.1.0
    - kaleido==0.2.1
    - mendeleev==0.15.0
    - pyfiglet==0.8.post1
    - rdkit==2022.9.5
